on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pull_request_job:
    runs-on: ubuntu-latest
    name: A job to validate a pull request
    steps:
    - name: Validate pull request step
      id: pull_request_action
      uses: lapitsky/hello-world-javascript-action/@master
      with:
        title_regex: '\\[ch\\d+\\]|\\[rp\\]|\\[hotfix\\]'
        github_token: "${{ secrets.GITHUB_TOKEN }}"
